# Generated by Django 3.2 on 2021-04-22 14:47

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutme',
            name='content',
            field=mdeditor.fields.MDTextField(),
        ),
    ]
