# Generated by Django 3.2 on 2021-04-20 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('password', models.TextField()),
                ('name', models.CharField(max_length=20)),
                ('mobile', models.CharField(max_length=13)),
                ('email', models.TextField()),
            ],
        ),
    ]
