# Generated by Django 3.2 on 2021-04-24 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('email', models.TextField()),
                ('message', models.TextField()),
                ('is_viewed', models.BooleanField()),
                ('is_deleted', models.BooleanField()),
            ],
        ),
    ]
