# Generated by Django 3.2 on 2021-04-19 06:49

from django.db import migrations, models

import utils.uploader


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CapabilityStack',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('rate', models.IntegerField()),
                ('is_using', models.BooleanField()),
                ('is_deleted', models.BooleanField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExternalSites',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.TextField()),
                ('title', models.CharField(max_length=20)),
                ('icon', models.ImageField(upload_to=utils.uploader.externalSitesIcons_uploadTo)),
                ('icon_selected', models.ImageField(upload_to=utils.uploader.externalSitesIcons_uploadTo)),
                ('is_using', models.BooleanField()),
                ('is_deleted', models.BooleanField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('introductions', models.TextField()),
                ('url', models.TextField()),
                ('online_url', models.TextField()),
                ('is_using', models.BooleanField()),
                ('is_deleted', models.BooleanField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20)),
                ('introduction', models.TextField()),
                ('start_time', models.DateField()),
                ('end_time', models.DateField()),
                ('is_now', models.BooleanField()),
                ('type', models.CharField(max_length=20)),
                ('is_using', models.BooleanField()),
                ('is_deleted', models.BooleanField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
