# Generated by Django 3.2 on 2021-04-19 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=20)),
                ('introduction', models.TextField()),
                ('birthday', models.DateField()),
                ('mobile', models.CharField(max_length=13)),
                ('email', models.CharField(max_length=13)),
                ('website', models.TextField()),
                ('address', models.TextField()),
                ('is_using', models.BooleanField()),
                ('is_deleted', models.BooleanField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
