# Generated by Django 3.2 on 2021-04-19 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_basicinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='title',
            field=models.TextField(),
        ),
    ]
