# Generated by Django 3.2 on 2021-04-22 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_alter_resume_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicinfo',
            name='email',
            field=models.TextField(),
        ),
    ]
