# Generated by Django 3.2 on 2021-05-01 09:07

import apps.resume.models
from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_alter_resume_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicinfo',
            name='personalImage',
            field=imagekit.models.fields.ProcessedImageField(null=True, storage=apps.resume.models.DataStorage(), upload_to=apps.resume.models.personalImage_uploadTo),
        ),
        migrations.AddField(
            model_name='basicinfo',
            name='personalQRCode',
            field=imagekit.models.fields.ProcessedImageField(null=True, storage=apps.resume.models.DataStorage(), upload_to=apps.resume.models.personalImage_uploadTo),
        ),
        migrations.AddField(
            model_name='basicinfo',
            name='vCard',
            field=models.FileField(null=True, storage=apps.resume.models.DataStorage(), upload_to=apps.resume.models.personalImage_uploadTo),
        ),
    ]
