# Generated by Django 3.2 on 2021-04-19 06:49

import django.db.models.deletion
from django.db import migrations, models

import utils.uploader


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCategories',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('parent_id', models.IntegerField(null=True)),
                ('is_deleted', models.BooleanField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('introduction', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('coverImage', models.ImageField(upload_to=utils.uploader.coverImage_uploadTo)),
                ('is_deleted', models.BooleanField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('cate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.articlecategories')),
            ],
        ),
    ]
