# Generated by Django 3.2 on 2021-04-23 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlecategories',
            name='is_using',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
