# Generated by Django 3.2 on 2021-04-23 05:43

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_articlecategories_is_using'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='content',
            field=mdeditor.fields.MDTextField(),
        ),
    ]
