# Generated by Django 3.2 on 2021-04-23 05:43

import utils.mdeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_articlecategories_is_using'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='content',
            field=utils.mdeditor.fields.MDTextField(),
        ),
    ]
