# Generated by Django 3.2 on 2021-04-23 17:17

import apps.articles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_alter_articles_coverimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='in_turn',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='articles',
            name='coverImage',
            field=models.FileField(storage=apps.articles.models.DataStorage(), upload_to=apps.articles.models.coverImage_uploadTo),
        ),
    ]
