# Generated by Django 3.2 on 2021-04-28 09:39

import apps.articles.models
from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0015_alter_articles_coverimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='coverImage',
            field=imagekit.models.fields.ProcessedImageField(null=True, storage=apps.articles.models.DataStorage(), upload_to=apps.articles.models.coverImage_uploadTo),
        ),
    ]
